version: "3.8"

services:
    web:
        build:
            context: .
            dockerfile: Dockerfile
        image: laravel_app
        container_name: laravel_web
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html # Monte le répertoire de l'application pour le développement en direct
        # networks:
        #     - app_network
# networks:
#     app_network:
#         driver: bridge
